# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

#    app.open_weather_api:
#        class:        Nfq\WeatherBundle\API\OpenWeather
#        arguments:    [%weather_api_key%]
#
#    nfq.weather:
#        class:        Nfq\WeatherBundle\Services\WeatherLoader
#        arguments:    ['@app.open_weather_api']
#
    app.yahoo_api:
        class:        Nfq\WeatherBundle\Providers\YahooWeather
#
#    nfq.weather2:
#        class:        Nfq\WeatherBundle\Services\WeatherLoader
#        arguments:    ['@app.yahoo_api']

    nfq_weather.provider.delegating:
        class:        Nfq\WeatherBundle\Services\WeatherLoader
        arguments:    ['%nfq_weather.delegating_providers%', '%ttl%', '%api_keys%']